apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginxandmysql-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /nginx
        backend:
          service:
            name: ingress-nginx-service
            port:
              number: 8000
      - pathType: Prefix
        path: /mysql
        backend:
          service:
            name: ingress-mysql-service
            port:
              number: 9000